spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
cloud:
  aws:
    stack:
      auto: false
    credentials:
      accessKey: ${AMAZON_ACCESS}
      secretKey: ${AMAZON_SECRET}
    region:
      static: sa-east-1
server:
  port: 5000